# code: language=ansible
#
# SPDX-License-Identifier: Apache-2.0
# Copyright Sensors & Signals LLC https://www.snstac.com/

- name: Include dhbridge tasks
  ansible.builtin.include_tasks: dhbridge.yml
