site_name: AryaOS
site_url: https://www.aryaos.org/
repo_url: https://github.com/snstac/aryaos
site_description: AryaOS Documentation
site_author: Greg Albrecht <gba@snstac.com>
copyright: Copyright Sensors & Signals LLC https://www.snstac.com/

theme:
  name: material
  highlightjs: true

nav:
  - Home: index.md
  - Introduction: intro.md
  - Installing AryaOS: install.md
  - Download or build: build.md
  - Agent handoff: agent-handoff.md
  - Configuration: config.md
  - Definitions: definitions.md
  - Troubleshooting: troubleshooting.md
  - AirTAK CUAS getting started: airtak_cuas_getting_started.md
  - Specifications: specs.md
  - Purchase: purchase.md
  - Changelog: changelog.md

plugins:
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - attr_list
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: True
