# CloudTAK web UI (SPA) — served behind lighttpd /cloudtak/ prefix strip.
# SPDX-License-Identifier: Apache-2.0

server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
