# code: language=ansible
#
# SPDX-License-Identifier: Apache-2.0
# Copyright Sensors & Signals LLC https://www.snstac.com/

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart dronehone-bridge
  ansible.builtin.systemd:
    name: dronehone-bridge.service
    state: restarted
