#!/bin/bash
#
# AryaOS config
#
# pi-gen config for AryaOS
#
# Copyright Sensors & Signals LLC https://www.snstac.com/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# shellcheck disable=SC2034
IMG_NAME="aryaos-$(git describe --exact-match --tags HEAD 2>/dev/null || git rev-parse --short HEAD)"
PI_GEN_RELEASE="AryaOS: The Operating System for Modern Situational Awareness."
TARGET_HOSTNAME="aryaos"
FIRST_USER_NAME="pi"
FIRST_USER_PASS="aryaos415"
STAGE_LIST="stage0 stage1 stage2 ../stage03-base ../stage04-wifi ../stage05-node-red ../stage06-common ../stage07-air ../stage08-sea ../stage09-uas ../stage10-docker"
DISABLE_FIRST_BOOT_USER_RENAME=1
RELEASE="bookworm"
WPA_ESSID="AryaOS-WiFi"
WPA_PASSWORD="aryaos415"
WPA_COUNTRY="US"
LOCALE_DEFAULT="en_US.UTF-8"
KEYBOARD_LAYOUT="English (US)"
KEYBOARD_KEYMAP="us"
ENABLE_SSH=1
APT_PROXY="http://172.17.2.88:3142"
# Hack: This is a workaround for the fact that the shared_files directory is not being copied to the build directory.
SHARED_FILES="../../../shared_files"
export SHARED_FILES="../../../shared_files"
