# code: language=ansible

- name: Restart lighttpd
  ansible.builtin.service:
    name: lighttpd
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload systemd for gpsd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Restart gpsd

- name: Restart gpsd socket
  ansible.builtin.service:
    name: gpsd.socket
    state: restarted
  listen: Restart gpsd

- name: Restart gpsd service
  ansible.builtin.service:
    name: gpsd
    state: restarted
  listen: Restart gpsd

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart GutCheck
  ansible.builtin.service:
    name: gutcheck
    state: restarted

- name: Reload systemd and restart lighttpd
  ansible.builtin.systemd:
    name: lighttpd
    daemon_reload: true
    state: restarted

- name: Restart tar1090
  ansible.builtin.service:
    name: tar1090
    state: restarted

- name: Restart dump1090-fa
  ansible.builtin.service:
    name: dump1090-fa
    state: restarted

- name: Restart dump978-fa
  ansible.builtin.service:
    name: dump978-fa
    state: restarted
