name: Build AryaOS Flows package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create package structure
        run: |
          mkdir -p .debpkg/home/node-red/.node-red
          cp ./shared_files/node-red/aryaos_flows.json .debpkg/home/node-red/.node-red/flows.json
          mkdir -p .debpkg/DEBIAN
          echo -e "chown node-red:node-red /home/node-red/.node-red/flows.json" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst

      - name: Run build-deb-action from jiro4989
        uses: jiro4989/build-deb-action@v3
        with:
          package: aryaos-flows
          package_root: .debpkg
          maintainer: gba@snstac.com
          version: ${{ github.ref_name }}
          arch: 'arm64'
          desc: 'Node-RED flows for AryaOS.'

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-deb
          path: |
            *.deb

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            *.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
